d /etc/hearth 0755 root root -
d /etc/hearth/agent 0700 root root -
d /var/lib/hearth 0755 root root -
d /var/lib/hearth/services 0755 root root -
d /var/lib/hearth/dnsmasq.d 0755 root root -
d /var/lib/hearth-agentd 0750 hearth-agent hearth -
d /var/log/hearth 0755 root root -
d /var/log/hearth-agentd 0750 hearth-agent hearth -
